# FashionGen data nums: 60147

includes:
- configs/models/fashionvil/defaults.yaml

dataset_config:
  fashiongen:
    use_images: true
    use_features: false

model_config:
  fashionvil:
    image_encoder:
      type: torchvision_resnet
      params:
        name: resnet50
        pretrained: true
        zero_init_residual: false
        num_output_features: -1
        pool_type: avg
    lr_multiplier: 20
    direct_features_input: false
    bert_model_name: bert-base-uncased
    training_head_type: contrastive
    bypass_transformer: true
    losses:
      - type: contrastive_loss

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 28170
    - 56340
    lr_ratio: 0.1
    warmup_iterations: 939
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8
    weight_decay: 1e-4

evaluation:
  metrics:
    - r@k_general

training:
  experiment_name: fashionvil_contrastive_fashiongen_e2e_pretrain_final
  batch_size: 64
  lr_scheduler: true
  max_updates: 75120
  log_interval: 10
  checkpoint_interval: 939
  evaluation_interval: 939
  early_stop:
    criteria: fashiongen/r@k_general/avg
    minimize: false
  wandb:
    enabled: true

run_type: train_val

checkpoint:
  resume_pretrained: true
  resume_file: save/fashionvil_e2e_pretrain_final/best.ckpt
  pretrained_state_mapping:
    image_encoder: image_encoder
    model.bert: model.bert
